services:
  web:
    build: .
    container_name: dovetail_flask_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    mem_limit: 600m
    mem_reservation: 256m # The baseline RAM allocated to the containerresources:
      