#in case of containerization
FROM python:3.9.1

# Set working directory inside the container
WORKDIR /CHESS

# Copy and install dependencies
COPY ./requirements.txt /CHESS/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /CHESS/requirements.txt

# Copy the rest of your app's files
COPY . .

# Expose Hugging Face's mandatory port and run with Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:7860", "main:app"]
